server_name: "Deerisle" # 服务器名称
port: 6969 # 端口号
mission: "empty.deerisle" # 地图任务
client_mods: [
    "@CF",
    "@DeerIsle",
    "@Code Lock",
    "@Ear-Plugs",
    "@Dabs Framework",
    "@Inventory Move Sounds",
    "@SkyZ - Skybox Overhaul",
    "@VPPAdminTools",
    "@Vehicle3PP",
    "@TerjePartyModTest",
    "@RaG_Core",
    "@RaG_BaseBuilding",
    "@FlipTransport",
    "@CoffeeDisableGardenplot",
    "@PerspectiveDeploy",
    "@Autorun Upgraded",
    "@BoomLay's Things",
    "@Boomlays Things Inventory Fix 1.27",
    "@Name Restrictor",
    "@Helicopter Mod",
    "@WindstridesClothingPack",
    "@DayZ-Expansion-Core",
    "@DayZ-Expansion-Licensed",
    "@DayZ-Expansion-Animations",
    "@DayZ-Expansion-Vehicles",
    "@Increased Lumens",
    "@Early Winter or late Fall in Chernarus",
    "@Early Winter or Late Fall Livonia",
    "@Snowy Trees for Early Winter Late Fall",
    "@Namalsk Survival",
    "@Realistic Walking Sounds",
    "@Lad's Lighting Overhaul",
    "@DZR Rags by hands",
    "@Basic Map",
  ] # 客户端模组
server_mods: ["@heli_server", "@ZombieSpawnTool"] # 服务器模组
