server_name: "Antoria" # 服务器名称
port: 6969 # 端口号
mission: "empty.Antoria" # 地图任务
client_mods: [
    "@CF",
    "@Code Lock",
    "@Ear-Plugs",
    "@Antoria_Addons_Dev",
    "@Antoria_Dev_edition",
    "@AntoriaPNC",
    "@AntoriaMap",
    "@DGBunker",
    "@RadZone",
    "@Inventory Move Sounds",
    "@SkyZ - Skybox Overhaul",
    "@VPPAdminTools",
    "@Vehicle3PP",
    "@TerjePartyModTest",
    "@RaG_Core",
    "@RaG_BaseBuilding",
    "@FlipTransport",
    "@CoffeeDisableGardenplot",
    "@PerspectiveDeploy",
    "@Autorun Upgraded",
    "@BoomLay's Things",
    "@Boomlays Things Inventory Fix 1.27",
    "@Name Restrictor",
    "@Helicopter Mod",
    "@WindstridesClothingPack",
    "@DF-Test",
    "@Simple Cinematics",
    "@Treasure",
    "@TreasurePhotosNamalsk",
    "@DayZ-Expansion-Core",
    "@DayZ-Expansion-Licensed",
    "@DayZ-Expansion-Animations",
    "@DayZ-Expansion-Vehicles",
    "@Increased Lumens",
  ] # 客户端模组
server_mods: ["@heli_server", "@ZombieSpawnTool"] # 服务器模组
